version: "3"
services:
  client:
    build: 
      context: client
      dockerfile: Dockerfile
    ports:
    - "80:3000"
    depends_on:
    - mongo

  serverapi:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
    - "5000:5000"
    depends_on:
    - mongo

  serversocket:
    build:
      context: server-socket
      dockerfile: Dockerfile
    ports:
    - "4444:4444"
    depends_on:
    - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"